# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pie < Formula
  desc "A tool for managing Python virtual environments."
  homepage "https://github.com/dhruvmanila/pie"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pie/releases/download/v0.9.0/pie-0.9.0-darwin-amd64.tar.gz"
      sha256 "9d59c1df6b53ec1bea7273c7042de4a8fdd5dc72eb78e1dac5222bd58dba2972"

      def install
        bin.install "pie"
        bash_completion.install "completions/pie.bash" => "pie"
        zsh_completion.install "completions/pie.zsh" => "_pie"
        fish_completion.install "completions/pie.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhruvmanila/pie/releases/download/v0.9.0/pie-0.9.0-darwin-arm64.tar.gz"
      sha256 "0a97f0714eb3ba76c9e840a6ead040d99f99c1a4fca1525aa2135555d70042ba"

      def install
        bin.install "pie"
        bash_completion.install "completions/pie.bash" => "pie"
        zsh_completion.install "completions/pie.zsh" => "_pie"
        fish_completion.install "completions/pie.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruvmanila/pie/releases/download/v0.9.0/pie-0.9.0-linux-arm64.tar.gz"
      sha256 "168ee520c52c8161aed53c0d289c4331ae20442d924462287535ed8bf7dc17c8"

      def install
        bin.install "pie"
        bash_completion.install "completions/pie.bash" => "pie"
        zsh_completion.install "completions/pie.zsh" => "_pie"
        fish_completion.install "completions/pie.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pie/releases/download/v0.9.0/pie-0.9.0-linux-amd64.tar.gz"
      sha256 "0c4dccb0a9e3960013ffa3f9703e35c9209637bc34b4a1d760e5c1d60ad888c9"

      def install
        bin.install "pie"
        bash_completion.install "completions/pie.bash" => "pie"
        zsh_completion.install "completions/pie.zsh" => "_pie"
        fish_completion.install "completions/pie.fish"
      end
    end
  end

  test do
    system "#{bin}/pie --version"
  end
end
