# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pie < Formula
  desc "A tool for managing Python virtual environments."
  homepage "https://github.com/dhruvmanila/pie"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhruvmanila/pie/releases/download/v0.10.0/pie-0.10.0-darwin-arm64.tar.gz"
      sha256 "ebdad585bb6d9238d242b9dae6e92ae1d34fad153d417838809ff631e58344c9"

      def install
        bin.install "pie"
        bash_completion.install "completions/pie.bash" => "pie"
        zsh_completion.install "completions/pie.zsh" => "_pie"
        fish_completion.install "completions/pie.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pie/releases/download/v0.10.0/pie-0.10.0-darwin-amd64.tar.gz"
      sha256 "e10406b08271a4a3f03805a258979c7e5cb82ec0b56ae0882d474867490cce2d"

      def install
        bin.install "pie"
        bash_completion.install "completions/pie.bash" => "pie"
        zsh_completion.install "completions/pie.zsh" => "_pie"
        fish_completion.install "completions/pie.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruvmanila/pie/releases/download/v0.10.0/pie-0.10.0-linux-arm64.tar.gz"
      sha256 "77ba9b8757450572d8fd54735ed8a74197b182728da3e9fe49cac791f7af7a7f"

      def install
        bin.install "pie"
        bash_completion.install "completions/pie.bash" => "pie"
        zsh_completion.install "completions/pie.zsh" => "_pie"
        fish_completion.install "completions/pie.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pie/releases/download/v0.10.0/pie-0.10.0-linux-amd64.tar.gz"
      sha256 "6145ef65d188d91060ad8d59989b7f3aa07a69bc9d259e22a990afa6287f9392"

      def install
        bin.install "pie"
        bash_completion.install "completions/pie.bash" => "pie"
        zsh_completion.install "completions/pie.zsh" => "_pie"
        fish_completion.install "completions/pie.fish"
      end
    end
  end

  test do
    system "#{bin}/pie --version"
  end
end
