# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pyvenv < Formula
  desc "Personal tool for managing Python virtual environments."
  homepage "https://github.com/dhruvmanila/pyvenv"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.4.3/pyvenv-0.4.3-darwin-amd64.tar.gz"
      sha256 "46d2a33f48609d54a750535fdb9ae40c67d28ee3c5616ec3447883fd253e8da6"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.4.3/pyvenv-0.4.3-darwin-arm64.tar.gz"
      sha256 "e5ecd8f790e13d818ea1d38be3211a49dc6542a5f8e67cb883b8d0e645c2b4d0"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.4.3/pyvenv-0.4.3-linux-amd64.tar.gz"
      sha256 "f434458401232da3ea4e432a557a9fa1c25041b84d74bf90151a909ad1505acc"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.4.3/pyvenv-0.4.3-linux-arm64.tar.gz"
      sha256 "63a643c57dc2e75b2a0a47e9497e77c861dbd299893cc34a16d37d36aff4e835"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
  end

  test do
    system "#{bin}/pyvenv --version"
  end
end
