# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pyvenv < Formula
  desc "Personal tool for managing Python virtual environments."
  homepage "https://github.com/dhruvmanila/pyvenv"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.4.1/pyvenv-0.4.1-darwin-amd64.tar.gz"
      sha256 "ae2220cdf2cb48dfb4d17fc4934816aff666ece6c84a6a015a576ea6fb9b3d18"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.4.1/pyvenv-0.4.1-darwin-arm64.tar.gz"
      sha256 "597b1fd51a856736daeeb75c06388507f877762aec6d5c93a541344055e17554"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.4.1/pyvenv-0.4.1-linux-arm64.tar.gz"
      sha256 "a3e900ad1f7fb5761b800a8352f79f2b0005e40b49abefe0678cd3fc2375e8ef"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.4.1/pyvenv-0.4.1-linux-amd64.tar.gz"
      sha256 "d85897180fe98806854b4ba5f33111a3886dac4079325ef0f127c16b3ff58f7d"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
  end

  test do
    system "#{bin}/pyvenv --version"
  end
end
