# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pyvenv < Formula
  desc "Personal tool for managing Python virtual environments."
  homepage "https://github.com/dhruvmanila/pyvenv"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.7.1/pyvenv-0.7.1-darwin-amd64.tar.gz"
      sha256 "45a23a01eabb3da2ecbe147bb989b708e82ed004458ea6423ad257486d12d122"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.7.1/pyvenv-0.7.1-darwin-arm64.tar.gz"
      sha256 "bb89e2da7904399867b9454dae84ef9406810fe76693ca4d3c57332016ff65f4"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.7.1/pyvenv-0.7.1-linux-amd64.tar.gz"
      sha256 "57824f749a6b7225b1b33734ce1d2f46ea5ff304741c97a2f8a28d74397b762b"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruvmanila/pyvenv/releases/download/v0.7.1/pyvenv-0.7.1-linux-arm64.tar.gz"
      sha256 "1124f58524089b4a12f71ab4a9a442073e2aff9540da1012a99c3c07860bb684"

      def install
        bin.install "pyvenv"
        bash_completion.install "completions/pyvenv.bash" => "pyvenv"
        zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
        fish_completion.install "completions/pyvenv.fish"
      end
    end
  end

  test do
    system "#{bin}/pyvenv --version"
  end
end
