---
project_name: pyvenv

before:
  hooks:
    - make tidy
    - ./scripts/gen-completions.sh

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{.CommitTimestamp}}"
    flags:
      - -trimpath
    ldflags:
      - -X main.version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "snapshot-{{ .Commit }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test"
      - "^chore"
      - Merge pull request
      - Merge branch

scoop:
  bucket:
    owner: dhruvmanila
    name: pyvenv
  folder: scoop
  commit_msg_template: "chore(scoop): update to version {{ .Tag }}"
  homepage: https://github.com/dhruvmanila/pyvenv
  description: Personal tool for managing Python virtual environments.
  license: MIT

brews:
  - tap:
      owner: dhruvmanila
      name: pyvenv
    folder: HomebrewFormula
    homepage: https://github.com/dhruvmanila/pyvenv
    commit_msg_template: "chore(brew): update to version {{ .Tag }}"
    description: Personal tool for managing Python virtual environments.
    license: MIT
    install: |
      bin.install "pyvenv"
      bash_completion.install "completions/pyvenv.bash" => "pyvenv"
      zsh_completion.install "completions/pyvenv.zsh" => "_pyvenv"
      fish_completion.install "completions/pyvenv.fish"
    test: |
      system "#{bin}/pyvenv --version"
